-- 061_hyde_analytics.sql
--
-- Add HyDE (Hypothetical Document Embedding) tracking to qa_analytics so we can
-- measure the retrieval quality impact of OLU-695 in production.
--
-- hyde_used=true means the query embedding was replaced with a hypothetical-answer
-- embedding generated by GPT-4o before Pinecone retrieval.  Joining this flag with
-- pinecone_scores lets us compare P@3 between hyde_used=true and hyde_used=false
-- cohorts on the abstract-query subset.

alter table qa_analytics
  add column if not exists hyde_used boolean default false;

comment on column qa_analytics.hyde_used is
  'True when HyDE (ENABLE_HYDE=true) replaced the raw query embedding with a hypothetical answer doc embedding for Pinecone retrieval.';
